services:
  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    networks:
      - terraform-provider-portainer_default
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

networks:
  terraform-provider-portainer_default:
    external: true
